version: '3'

# Use these volumes for development only.
volumes:
    mongo-raw-message-db-mongodata:
        name: mongo-raw-message-db-mongodata


services:

    mongo-raw-message-db:

        container_name: mongo-raw-message-db

        build:
            context: ./source

        ports:
            - "${MONGODB_PORT}:27017"

        volumes: 
            - "mongo-raw-message-db-mongodata:/data/db"

        user: "${USER_ID}:${GROUP_ID}"

        environment:
            - "MQTT_BROKER_HOST=${MQTT_BROKER_HOST}"
            - "MQTT_BROKER_PORT=${MQTT_BROKER_PORT}"
            - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}"
            - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}"
            - "MONGO_USERNAME=${MONGO_USERNAME}"
            - "MONGO_PASSWORD=${MONGO_PASSWORD}"
            - "MONGO_LOGIN_DB=${MONGO_LOGIN_DB}"
            - "MQTT_TOPIC_ALL_RAW_MESSAGES=+/raw_message_to_db"
            - "MQTT_INTEGRATION_LOG_LEVEL=DEBUG"

        restart: always
