version: '3'

services:

    django-api:
        container_name: django-api
        build:
            context: ./source
        restart: always
        user: "${USER_ID}:${GROUP_ID}"
        ports:
            - "8080:8080"
            - "8443:8443"
        volumes:
            - ./source/api:/source/api
        environment:
            - "MQTT_BROKER_HOST=${MQTT_BROKER_HOST}"
            - "MQTT_BROKER_PORT=${MQTT_BROKER_PORT}"
            - "LOGLEVEL=${LOGLEVEL}"
            - "DJANGO_DEBUG=${DJANGO_DEBUG}"
            - "DJANGO_ADMINS=${DJANGO_ADMINS}"
            - "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}"
            - "FQ_HOSTNAME=${FQ_HOSTNAME}"
            - "SSL_CERT_PEM=${SSL_CERT_PEM}"
            - "SSL_KEY_PEM=${SSL_KEY_PEM}"
            - "DATABASE_SETTING=${DATABASE_SETTING}"
            - "N_CMI_WRITE_THREADS=${N_CMI_WRITE_THREADS}"

    # Allows local testing.
    django-api-devl-broker:
        container_name: "django-api-devl-broker"
        image: bemcom/mosquitto-mqtt-broker:0.1.0
        restart: always
        user: "${USER_ID}:${GROUP_ID}"
        ports:
            - "1883:1883"
