version: '3'

services:

    django-api:

        container_name: django-api

        build:
            context: ./source

        restart: always

        ports:
            - "8000:8000"

        volumes:
            - ./source/api:/source/api

        user: "${USER_ID}:${GROUP_ID}"

        environment:
            - "MQTT_BROKER_HOST=${MQTT_BROKER_HOST}"
            - "MQTT_BROKER_PORT=${MQTT_BROKER_PORT}"
            - "LOGLEVEL=${LOGLEVEL}"
            - "DJANGO_DEBUG=${DJANGO_DEBUG}"
            - "DJANGO_ADMINS=${DJANGO_ADMINS}"
            - "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}"
            - "HOSTNAME=${HOSTNAME}"
            - "SSL_CERT_PEM=${SSL_CERT_PEM}"
            - "SSL_KEY_PEM=${SSL_KEY_PEM}"
            - "DATABASE_SETTING=${DATABASE_SETTING}"
