version: '3'

services:

    mongo-raw-message-db:

        container_name: mongo-raw-message-db

        build:
            context: ./source

        ports:
            - "${MONGODB_PORT}:27017"

        volumes: 
            - "${MONGODB_VOLUME}:/data/db"

        user: "${USER_ID}:${GROUP_ID}"

        environment:
            - "MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}"
            - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}"
            - "MONGO_USERNAME=${MONGO_USERNAME}"
            - "MONGO_PASSWORD=${MONGO_PASSWORD}"
            - "MQTT_BROKER_HOST=${MQTT_BROKER_HOST}"
            - "MQTT_BROKER_PORT=${MQTT_BROKER_PORT}"
            - "MQTT_TOPIC_ALL_RAW_MESSAGES=+/raw_message_to_db"
            - "MQTT_INTEGRATION_LOG_LEVEL=DEBUG"

        restart: always
