version: '3'

services:
    message-broker:
        container_name: message-broker
        image: "eclipse-mosquitto:1.5.4"
        user: "${USER_ID}:${GROUP_ID}"
        restart: always

    aquametro-ambus-net-connector:
        ports:
            - 8206:1880
        image: bemcom/aquametro-ambus-net-connector:0.1.0
        restart: always
        environment:
            - CONNECTOR_NAME=aquametro-ambus-net-connector
            - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
            - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
            - SEND_RAW_MESSAGE_TO_DB=${SEND_RAW_MESSAGE_TO_DB}
            - AMBUSNETWS_SOAP_URL=http://141.21.47.85/AmbusNetWS/Service1.asmx
            - METER_IDS=[1, 2, 3, 4, 5, 120]
            - POLL_SECONDS=30
            - MAX_POLLS_PER_PERIOD=15

    keba-p30-connector-aussen:
        ports:
            - 8207:1880
            - 7090:7090

        image: bemcom/keba-p30-connector:0.0.1
        restart: always
        environment:
            - CONNECTOR_NAME=keba-p30-connector-aussen
            - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
            - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
            - SEND_RAW_MESSAGE_TO_DB=${SEND_RAW_MESSAGE_TO_DB}
            - KEBA_P30_URL=iik-ladesaeule-aussen.fzi.de
