version: '3'

services:
    ocpp-connector:
        container_name: ocpp-connector
        build:
            context: ./source
        restart: always
        user: "${USER_ID}:${GROUP_ID}"
        environment:
            - CONNECTOR_NAME=ocpp-connector
            - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
            - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
            - SEND_RAW_MESSAGE_TO_DB=${SEND_RAW_MESSAGE_TO_DB}
            - DEBUG=${DEBUG}
            - OCPP_PORT=${OCPP_PORT}
            - OCPP_CONFIG=${OCPP_CONFIG}
