version: '3'

services:
    brand-new-connector:
        container_name: brand-new-connector
        build:
            context: ./source
        restart: always
        volumes: 
            - ./source/connector/:/source/connector/
        user: "${USER_ID}:${GROUP_ID}"
        environment:
            - CONNECTOR_NAME=brand-new-connector
            - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
            - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
            - SEND_RAW_MESSAGE_TO_DB=${SEND_RAW_MESSAGE_TO_DB}
            - DEBUG=${DEBUG}
