version: '3'

services:
    python-connector-template:
        container_name: python-connector-template
        build:
            context: ./source
        restart: always
        user: "${USER_ID}:${GROUP_ID}"
        environment:
            - CONNECTOR_NAME=python-connector-template
            - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
            - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
            - SEND_RAW_MESSAGE_TO_DB=${SEND_RAW_MESSAGE_TO_DB}
            - DEBUG=${DEBUG}
