version: '3'

services:

    django-api:

        container_name: django-api

        build:
            context: ./source

        restart: always

        ports:
            - "8000:8000"

        volumes:
            - ./source/django_code:/bemcom/code
#            - /source/db:/bemcom/db

        user: "${USER_ID}:${GROUP_ID}"

        environment:
            - "MQTT_BROKER_HOST=${MQTT_BROKER_HOST}"
            - "MQTT_BROKER_PORT=${MQTT_BROKER_PORT}"
            - "MODE=${MODE}"
            - "DJANGO_ADMINS=${DJANGO_ADMINS}"
            - "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}"
            - "HOSTNAME=${HOSTNAME}"
            - "SSL_CERT_PEM=${SSL_CERT_PEM}"
            - "SSL_KEY_PEM=${SSL_KEY_PEM}"

# This is a tool for developing the OpenAPI specification of the API.
# See also: https://swagger.io/tools/open-source/the-new-swagger-editor-and-swagger-ui/
    swagger-editor:
        
        container_name: django-api-swagger-editor

        image: swaggerapi/swagger-editor:latest

        ports:
            - "7999:8080"

        volumes:
            - ./source/openapi:/usr/share/nginx/html/django-api
