version: '3'

services:

    django-api:

        container_name: django-api

        build:
            context: ./source

        restart: always

        ports:
            - "8000:8000"

        volumes:
            - ./source/django_code:/bemcom/code
            - /tmp/db.sqlite3:/bemcom/db.sqlite3

        user: "${USER_ID}:${GROUP_ID}"

        environment:
            - "MQTT_BROKER_HOST=${MQTT_BROKER_HOST}"
            - "MQTT_BROKER_PORT=${MQTT_BROKER_PORT}"
            - "MODE=${MODE}"

