apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bemcom-app.fullname" . }}-django-api
  namespace: {{ .Release.Namespace }}
data:
  DJANGO_SECRET_KEY: {{ .Values.djangoApi.deployment.api.secrets.DJANGO_SECRET_KEY | b64enc | quote }}
  DJANGO_SUPERUSER_USERNAME: {{ .Values.djangoApi.deployment.api.secrets.DJANGO_SUPERUSER_USERNAME | b64enc | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.djangoApi.deployment.api.secrets.DJANGO_SUPERUSER_PASSWORD | b64enc | quote }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.djangoApi.deployment.api.secrets.DJANGO_SUPERUSER_EMAIL | b64enc | quote }}
  DJANGOAPIDB_USER: {{ .Values.djangoApi.deployment.db.secrets.POSTGRES_USER | b64enc | quote }}
  DJANGOAPIDB_PASSWORD: {{ .Values.djangoApi.deployment.db.secrets.POSTGRES_PASSWORD | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bemcom-app.fullname" . }}-django-api-db
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_USER: {{ .Values.djangoApi.deployment.db.secrets.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.djangoApi.deployment.db.secrets.POSTGRES_PASSWORD | b64enc | quote }}
---
{{- if .Values.grafanaTool.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bemcom-app.fullname" . }}-grafana-tool
  namespace: {{ .Release.Namespace }}
data:
  GF_SECURITY_ADMIN_USER: {{ .Values.grafanaTool.deployment.secrets.GF_SECURITY_ADMIN_USER | b64enc | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafanaTool.deployment.secrets.GF_SECURITY_ADMIN_PASSWORD | b64enc | quote }}
{{ end }}
---
{{- if .Values.mongoRawMessageDb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bemcom-app.fullname" . }}-mongo-raw-message-db
  namespace: {{ .Release.Namespace }}
data:
  MONGO_USERNAME: {{ .Values.mongoRawMessageDb.deployment.secrets.MONGO_USERNAME | b64enc | quote }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongoRawMessageDb.deployment.secrets.MONGO_USERNAME | b64enc | quote }}
  MONGO_PASSWORD: {{ .Values.mongoRawMessageDb.deployment.secrets.MONGO_PASSWORD | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongoRawMessageDb.deployment.secrets.MONGO_PASSWORD | b64enc | quote }}
  MONGO_LOGIN_DB: {{ .Values.mongoRawMessageDb.deployment.secrets.MONGO_LOGIN_DB | b64enc | quote }}
{{ end }}
