version: '3'

services:
    keba-p30-connector:
        container_name: keba-p30-connector
        build:
            context: ./source
        restart: always
        ports:
            - 8207:1880
            - 7090:7090
        environment:
            - CONNECTOR_NAME=keba-p30-connector
            - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
            - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
            - SEND_RAW_MESSAGE_TO_DB=${SEND_RAW_MESSAGE_TO_DB}
            - KEBA_P30_URL=${KEBA_P30_URL}
