version: '3'

services:
    keba-p30-connector:
        container_name: keba-p30-connector
        build:
            context: ./source
        restart: always
        volumes: 
            - ./source/connector/:/source/connector/
        user: "${USER_ID}:${GROUP_ID}"
        environment:
            - CONNECTOR_NAME=keba-p30-connector
            - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
            - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
            - SEND_RAW_MESSAGE_TO_DB=${SEND_RAW_MESSAGE_TO_DB}
            - DEBUG=${DEBUG}
            - POLL_SECONDS=${POLL_SECONDS}
            - KEBA_P30_CHARGE_STATIONS=${KEBA_P30_CHARGE_STATIONS}
        network_mode: host
