version: '3'

services:
    homematic-connector:
        container_name: homematic-connector
        ports:
            - 8208:1880
            - "${CALLBACK_BINRPC_PORT_IIK}:${CALLBACK_BINRPC_PORT_IIK}"
            - "${CALLBACK_XMLRPC_PORT_IIK}:${CALLBACK_XMLRPC_PORT_IIK}"
        build:
            context: ./source
        restart: always
        ports:
            - 8205:1880
            - "${CALLBACK_BINRPC_PORT}:${CALLBACK_BINRPC_PORT}"
            - "${CALLBACK_XMLRPC_PORT}:${CALLBACK_XMLRPC_PORT}"
        environment:
            - CONNECTOR_NAME=homematic-connector
            - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
            - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
            - SEND_RAW_MESSAGE_TO_DB=${SEND_RAW_MESSAGE_TO_DB}
            - CCU_DNS_NAME=${CCU_DNS_NAME}
            - CALLBACK_DNS_NAME=${CALLBACK_DNS_NAME}
            - CALLBACK_BINRPC_PORT=${CALLBACK_BINRPC_PORT}
            - CALLBACK_XMLRPC_PORT=${CALLBACK_XMLRPC_PORT}
