version: '3'

services:

    homematic-connector:

        ports:
            - 8205:1880
            - "${CALLBACK_BINRPC_PORT}:${CALLBACK_BINRPC_PORT}"
            - "${CALLBACK_XMLRPC_PORT}:${CALLBACK_XMLRPC_PORT}"

        build:
            context: ./source

        restart: always

        environment:
            - CONNECTOR_NAME=homematic-connector
            - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
            - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
            - SEND_RAW_MESSAGE_TO_DB=${SEND_RAW_MESSAGE_TO_DB}
            - CCU_DNS_NAME=${CCU_DNS_NAME}
            - CALLBACK_DNS_NAME=${CALLBACK_DNS_NAME}
            - CALLBACK_BINRPC_PORT=${CALLBACK_BINRPC_PORT}
            - CALLBACK_XMLRPC_PORT=${CALLBACK_XMLRPC_PORT}
