version: "3"

services:
    grafana-tool:
        container_name: grafana-tool 
        build:
            context: ./source
        restart: always
        ports:
            - 3000:3000
        #volumes:
        #    - ./souce/graf_data/plugins/holl-rest-api:/var/lib/grafana/plugins/holl-rest-api
        environment:
            - "GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}"
            - "GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}"
