version: "3"

services:
  grafana-tool:
    container_name: grafana-tool
    build:
      context: ./source
    restart: always
    ports:
      - 3000:3000
    #volumes:
      # production
      # - "${GRAFANA_DB_FILE:-./grafana.db}:/var/lib/grafana/grafana.db"
      # development:
      # - ./source/grafana_plugins/bemcom-django-api/dist:/var/lib/grafana-plugins/bemcom-django-api
      # - ./source/grafana_plugins/nwpdata-service-api/dist:/var/lib/grafana-plugins/nwpdata-service-api
      # - ./source/grafana_plugins/prediction-service-api/dist:/var/lib/grafana-plugins/prediction-service-api
    user: "${USER_ID}:${GROUP_ID}"
    environment:
      - "GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-bemcom}"
      - "GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-bemcom}"
