version: "3"

services:
  grafana-holl-rest-api:
    image: grafana/grafana:latest
    container_name: grafana-holl-rest-api
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./graf_data/plugins/holl-rest-api:/var/lib/grafana/plugins/holl-rest-api
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
