version: "3"
networks:
  graf_test:
    name: graf-test
#    driver: default

services:
  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   expose:
  #     - 3000
  #     - 3001
  #     - 80
  #   ports:
  #     - 80:80
  #     - 3000:3000
  #     - 3001:3001
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - graf_test

  graf:
    image: grafana/grafana:latest
    container_name: graf
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_SECURITY_ADMIN_USER: admin
    volumes:
      - ./graph_data:/var/lib/grafana
    networks:
      - graf_test

  # fake-api:
  #   image: test/fake-api
  #   container_name: fake_api
  #   expose:
  #     - 3333
  #   ports:
  #     - 3333:3333
  #   networks:
  #     - graf_test
