version: '3'

services:
    aquametro-ambus-net-connector:

        ports:
            - 8206:1880

        build:
            context: ./source

        restart: always

        environment:
            - CONNECTOR_NAME=aquametro-ambus-net-connector
            - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
            - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
            - SEND_RAW_MESSAGE_TO_DB=${SEND_RAW_MESSAGE_TO_DB}
            - AMBUSNETWS_SOAP_URL=${AMBUSNETWS_SOAP_URL}
            - METER_IDS=${METER_IDS}
            - POLL_SECONDS=${POLL_SECONDS}
            - MAX_POLLS_PER_PERIOD=${MAX_POLLS_PER_PERIOD}
